allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.buildDir = '../build'
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}
subprojects {
    project.evaluationDependsOn(':app')
}

flutterflow
task clean(type: Delete) {
tasks.register("clean", Delete) { main
    delete rootProject.buildDir
}
